version: "3.9"

services:
  tarantool1:
    build: ./
    ports:
      - "3301:3301"
    networks:
      - tarantool
    hostname: "tarantool"
    volumes:
      - "./var_lib_tarantool:/var/lib/tarantool"
      - "./opt_tarantool:/opt/tarantool"
    command: ["tarantool", "/opt/tarantool/app.lua"]

networks:
  tarantool:
    name: "tarantool"
